In [5]:
import pandas as pd

In [6]:
keyname = 'Mt'
path = '/Users/dongjiacheng/Desktop/coder/mtd/RNA-seq/'+ keyname +'/'
print(path)

/Users/dongjiacheng/Desktop/coder/mtd/RNA-seq/Mt/

In [7]:
exp_df = pd.read_csv(path + keyname + '_5_exp.tsv', sep='\t').copy()
sample_df = pd.read_csv(path + keyname + '_6_sample.tsv', sep='\t').copy()

# 将Temperature空值设置为''
sample_df['Temperature'] = sample_df['Temperature'].fillna('')
sample_df['Carbon Sources'] = sample_df['Carbon Sources'].fillna('')
sample_df['Time'] = sample_df['Time'].fillna('')

# 将Sample ID、Strain、Carbon Sources、Temperature、Time的值组合成新的列名
sample_df['New_Column_Name'] = sample_df['Sample ID'] + ' ' + sample_df['Strain'] + ' ' + sample_df['Carbon Sources'] + ' ' + sample_df['Temperature'] + ' ' + sample_df['Time'].astype(str)

# 创建一个映射字典
rename_dict = sample_df.set_index('Sample ID')['New_Column_Name'].to_dict()

# 使用字典重命名exp.tsv的列名
exp_df.rename(columns=rename_dict, inplace=True)

# 查看更改后的exp.tsv
exp_df

,Gene id,mt004001 WT Glucose 37° 2h,mt004002 WT Xylose 37° 2h,mt004003 WT Arabinose 37° 2h,mt004004 WT Arabinoxylan 37° 2h,mt004005 WT Arabinoxylan 37° 8h,mt004006 Xyr1 mutant Glucose 37° 2h,mt004007 Xyr1 mutant Xylose 37° 2h,mt004008 Xyr1 mutant Arabinose 37° 2h,mt004009 Xyr1 mutant Arabinoxylan 37° 2h,...,mt003003 WT Starch 45° 4h,mt005001 Mtclr Nocarbon 45° 4h,mt005002 WT Nocarbon 45° 4h,mt006001 WT Avicel 45° 2 or 4d,mt006002 JG141 Avicel 45° 2 or 4d,mt006003 JG207 Avicel 45° 2 or 4d,mt006004 JG207Ncclr2 Avicel 45° 2 or 4d,mt006005 JG336 Avicel 45° 2 or 4d,mt006006 WT Glucose 45° 2 or 4d,mt006007 JG207 Glucose 45° 2 or 4d
0,MYCTH_2114025,6.32,7.74,8.23,5.81,5.03,7.10,8.08,7.50,4.63,...,3.06,0.81,1.23,3.38,6.84,2.94,3.54,8.18,1.80,4.10
1,MYCTH_2293935,3.54,2.60,1.25,1.75,2.42,3.36,3.50,1.33,1.48,...,0.88,0.16,0.60,4.94,4.92,1.92,1.87,4.08,0.97,1.90
2,MYCTH_2293936,0.87,0.51,0.55,0.37,1.45,0.95,0.58,0.09,0.50,...,0.69,0.30,1.23,5.65,1.44,1.82,1.20,1.19,0.50,0.46
3,MYCTH_2051335,10.88,7.86,9.88,7.50,7.14,11.56,7.68,7.88,11.90,...,12.23,4.53,7.96,12.96,25.00,8.61,12.56,15.57,7.58,10.42
4,MYCTH_2121898,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9287,MYCTH_103797,0.05,0.43,0.64,0.10,0.19,0.07,0.48,0.37,3.69,...,0.46,1.40,0.68,2.20,2.96,1.70,2.50,1.16,0.56,1.02
9288,MYCTH_2071098,3.25,2.56,2.92,2.02,4.14,2.44,2.24,2.58,4.47,...,12.18,5.58,5.98,6.19,10.60,5.43,7.08,8.68,8.82,7.56
9289,MYCTH_2114022,0.12,0.00,0.00,0.00,0.00,0.12,0.00,0.00,0.06,...,0.30,0.00,0.00,0.14,0.08,0.10,0.02,0.03,0.04,0.08
9290,MYCTH_2114023,0.14,0.00,0.07,0.06,0.20,0.00,0.13,0.06,0.07,...,1.32,0.28,0.46,0.61,0.70,0.43,0.38,0.82,0.66,0.32
9291,MYCTH_2313233,27.84,14.38,18.13,23.04,15.77,23.24,11.46,18.23,22.28,...,22.24,15.65,18.10,24.97,16.72,20.32,15.14,23.47,17.74,15.79

In [8]:
# 保存exp_df为tsv
exp_df.to_csv(path + keyname + '_7_exp_condition.tsv', sep='\t', index=False)